# Generated by Django 4.1 on 2023-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='task',
            field=models.ManyToManyField(related_name='tasks', to='dashboards.task'),
        ),
    ]
