# Generated by Django 4.1 on 2023-05-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
        ('dashboards', '0002_alter_supervisor_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actstream.action',),
        ),
    ]
